name = "3dcookiehd-education-platform"
main = "src/index.tsx"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "education-platform-db"
database_id = "28fc5bec-bc18-46a9-8aea-fc4a4f6e44db"

[build]
command = "npm run build"

