-- PDF(와우쓰리디홍대센터_WOW3D 교육과정소개_251024) Part 04 교육실적 추출 데이터
-- 실행: wrangler d1 execute <DB> --remote --file=./migrations/0084_seed_education_performance_from_pdf.sql

INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2015. 07', '2015-6차 직업능력개발훈련 통합심사 과정 인정 및 진행', 0);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 02', '(사)3D프린팅산업협회 공인교육기관 지정', 1);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 03', '국비지원 3D프린터 조립전문가 교육진행', 2);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 03', '국비지원 3D프린팅 마스터 교육진행', 3);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 07', '2016-6차 직업능력개발훈련 통합심사 과정 인정 및 진행', 4);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 08', '미래인재교육개발원_공무원 연수 1', 5);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 09', 'LG화학 임원진 3D프린팅 체험', 6);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 09', '덕원중학교 3D프린팅 진로체험학습', 7);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 09', '화원중학교 3D프린팅 진로체험학습', 8);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 09', '동양고등학교 3D프린팅 현장직업체험교육', 9);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 10', '홍익디자인 고등학교 교직원 대상 3D프린팅 교육 1', 10);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 10', '미래인재교육개발원_공무원 연수 2', 11);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 10', '드림잡페스티벌_진로체험', 12);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 10', '의정부 서중학교 3D프린팅 진로체험학습', 13);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 11', '김포고등학교 3D프린팅 체험학습', 14);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 11', '김포운양중학교 3D프린팅 체험학습', 15);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 12', '화곡고등학교 진로체험 학습', 16);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 12', '2016-9차 직업능력개발훈련 통합심사 과정 인정 및 진행', 17);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2016. 12', '홍익디자인 고등학교 교직원 대상 3D프린팅 교육 2', 18);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2017. 05', '백송고등학교 3D프린팅 진로체험학습', 19);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2017. 07', '2017-6차 직업능력개발훈련 통합심사 과정 인정 및 진행', 20);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2017. 08', '광탄고등학교 3D프린팅 진로체험학습', 21);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2017. 08', '한밭대학교 3D프린팅 전문교강사 자격증 취득과정', 22);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2017. 08', '사)3D프린팅산업협회 3D프린팅 교육', 23);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2017. 10', '사)3D프린팅산업협회 3D프린팅 교육', 24);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2017. 12', '2017-9차 직업능력개발훈련 통합심사 과정 인정 및 진행', 25);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2017. 12', '광운대학교 3D프린팅마스터 자격증 취득과정', 26);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2017. 12', '광명고등학교 전교생 대상 3D프린팅 진로체험학습', 27);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 01', '금오공과대학교 3D프린팅전문교강사 자격증 취득과정', 28);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 01', '광운대학교 3D프린팅마스터 자격증 취득과정', 29);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 01', '순천향대학교 3D프린팅마스터 자격증 취득과정', 30);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 02', '대전계룡 디지텍 고등학교 교사 대상 교육', 31);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 04', '안동지식재산센터IP창업 8기', 32);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 04', '대구 경북 중소기업청 창업교육', 33);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 04', '사)3D프린팅산업협회 경북 특화교육 3D프린팅 마스터/조립 자격증 교육', 34);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 05', '백송고등학교 진로체험 학습', 35);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 06', '마곡 중학교 진로체험 학습', 36);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 06', '동남보건대학교 3D프린팅 자격증 과정', 37);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 07', '광운대학교 3D프린팅마스터 자격증 취득과정 1차', 38);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 07', '순천향대학교 3D프린팅마스터 자격증 취득과정', 39);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 07', '사)3D프린팅산업협회 3D프린팅 마스터/조립 자격증 교육', 40);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 08', '사)3D프린팅산업협회 경북특화교육 3D프린팅 마스터/조립 자격증 교육', 41);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 08', '금오공과대학교 3D프린팅마스터 자격증 취득과정', 42);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 08', '경북보건대학교 3D프린팅 교육', 43);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 08', '평택 방과후 교사 대상 특강', 44);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 08', '광운대학교 3D프린팅마스터 자격증 취득과정 2,3차', 45);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 10', '포스텍나노융합기술원 ACU 국제인증자격시험대비 및 시험진행', 46);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 10', '포천영북중학교 진로체험 학습', 47);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 10', '오산엘지화학 임직원 대상 교육', 48);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 10', '광명소하중학교 3D프린팅 진로체험학습', 49);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 10', '광명고등학교 1학년 대상 3D프린팅 진로체험학습', 50);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 11', '사)3D프린팅산업협회 경북특화교육', 51);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 12', '포스텍나노융합기술원 ACU 국제인증자격시험대비 및 시험진행', 52);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 12', '포스텍나노융합기술원 DLP 방식 3D프린터 활용 Real 쥬얼리 과정', 53);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 12', '[아산시청] 고교생 대상 3D프린팅 진로체험 학습', 54);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 12', '평택 이충고등학교 3D프린팅 진로체험 학습', 55);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 12', '포스텍나노융합기술원 3D프린터 조립전문가 교육', 56);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 12', '사)3D프린팅산업협회 ACU 국제인증자격시험대비 및 시험진행', 57);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 12', '수원 고현초등학교 3D프린팅 진로체험 학습', 58);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 12', '청평중학교 3D프린팅 진로체험 학습', 59);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 12', '대경 대학교 DLP 방식 3D프린터 활용 Real 쥬얼리 과정', 60);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2018. 12', '사)3D프린팅산업협회 DLP 방식 3D프린터 활용 Real 쥬얼리 과정', 61);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 01', '순천향대학교 3D프린팅 마스터 교육', 62);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 01', '수원고색초등학교 3D프린팅 진로체험 학습', 63);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 02', '금오공대 ACU 국제인증자격시험대비 및 시험진행', 64);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 03', '김포고등학교 3D프린팅 진로체험 학습', 65);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 04', '김포 통진고등학교 3D프린팅 진로체험 학습', 66);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 05', '김포안곡고등학교 3D프린팅 진로체험 학습', 67);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 06', '금오공대 ACU 국제인증자격시험대비 및 시험진행', 68);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 06', '광운대학교 3D프린팅 마스터과정 및 시험진행', 69);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 06', '마곡중학교 3D프린팅 진로체험 학습', 70);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 06', '대전보건대학교 3D프린팅 마스터과정 및 시험진행', 71);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 06', '경운대 ACU 국제인증자격시험대비 및 시험진행', 72);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 06', '수원 산남중학교 학생 대상 3D프린팅 체험학습', 73);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 06', '금오공대 학부생 및 일반인 대상 ACA Photoshop CS6 국제인증자격시험 대비 교육', 74);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', '포항나노융합기술원 ACU 국제인증자격시험대비 및 시험진행', 75);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', '광운대학교 3D프린팅 마스터과정 및 시험진행', 76);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', '포항나노융합기술원 3D프린팅 마스터과정 및 시험진행', 77);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', '사)3D프린팅 산업협회 ACU 국제인증자격시험대비 및 시험진행', 78);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', '경기 KICT 3D프린팅 제품 제작과정', 79);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', 'K-ICT 경기센터, Maker를 위한 Fusion360 및 FDM 3D프린팅 활용교육 1기', 80);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', '의정부 경민중학교 3D프린팅 진로체험학습', 81);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', '순천향대학교 3D프린팅 마스터 특강', 82);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', '3D프린팅 산업협회 특화교육 ACA Photoshop CS6 국제인증자격시험 대비 과정', 83);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', 'KICT 경기센터 씨앗 메이커스 회천중학교 3D프린팅 진로체험학습', 84);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', 'KICT 경기센터 씨앗 메이커스 효자중학교 3D프린팅 진로체험학습', 85);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', 'K-ICT 경기센터, Maker를 위한 Fusion360 및 FDM 3D프린팅 활용교육 2기', 86);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', '광운대 SNK비타민센터 3D프린팅 전문가 자격교육 3기', 87);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 07', '광명고등학교 1학년 학생 대상 3D프린팅 진로체험학습', 88);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 08', '구미 경구고등학교 3D프린팅 교육', 89);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 08', '경북보건대 3D프린팅 마스터/조립 2급 자격과정', 90);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 08', '광운대 SNK-비타민센터 3D프린팅 장비 기초교육', 91);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 09', '서일대학교 3D프린팅 입문교육', 92);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 09', '광운대학교 비타민SNK센터 3D프린팅 장비기초 교육', 93);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 11', '경운대학교 3D프린팅 창업기술 교육과정(쥬얼리제작)', 94);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 11', '경운대학교 퓨전360 모델링 드론설계과정', 95);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 11', '경운대학교 3D프린팅 전문인력 양성과정 경북특화 이론 및 실습교육', 96);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 11', '연세대학교 원주캠퍼스 3D프린팅 마스터 교육과정', 97);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 12', '서일대 3D프린팅을 위한 모델링-퓨전 360 ACU 국제인증자격시험 대비반', 98);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 12', '포항나노융합기술원 포철공고 학생 대상 ACU 국제자격증 대비 및 시험응시', 99);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 12', '경북 ICT&메카트로닉스산업 재직자인력양성사업, 3D프린팅을 활용한 제품설계 및 시제품 개발 과정', 100);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 12', '포항나노융합기술원 포철공고 학생 대상 3D프린팅 마스터 자격증 대비 및 시험응시', 101);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 12', '광운대학교 SNK-비타민센터 3D프린팅 전문가 자격교육 4기', 102);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 12', '성암국제무역고등학교 포터블 3D프린터 미니 특강', 103);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2019. 12', '광운대학교 SNK-비타민센터 3D프린팅 전문가 자격교육 5기', 104);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 02', '순천향 대학교 3D프린팅 교육 및 자격증 시험', 105);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 06', '구미여성인력센터 ACU_AutoCAD 국제자격시험', 106);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 07', '서일대학교 Made in seoil 3D프린팅 입문교육', 107);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 07', '아현중학교 3D프린팅 반지만들기 체험학습', 108);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 07', '포항공대 나노융합기술원 ACU 국제자격증 과정', 109);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 08', '구미 3D프린터 운용기능사 실기대비 특강', 110);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 09', '포스텍나노융합기술원 ACU 국제인증자격증 과정', 111);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 09', '경운대학교 퓨전360을활용한제품설계 및 3D프린팅 블랜디드 수업', 112);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 10', '광운창작소_창작아카데미의 캐릭터 크리에이터 : 3D캐릭터 제작 온라인 교육', 113);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 10', '광운대학교 3D프린터 장비교육 1기, 2기', 114);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 11', '김포 신양중학교 3D프린팅 미래직업 체험활동', 115);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 11', '운양중학교 3D프린팅 진로 체험학습', 116);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 11', '용산공업고등학교 학생 대상 3D스캐닝 및 데이터 편집(스컬프트리스)하여 흉상 만들기 과정', 117);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2020. 12', '강서공업고등학교 교직원 대상 퓨전360 수업', 118);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2021. 02', '[블랜디드 수업]금오공대-퓨전360활용 제품제작 및 ACU 자격증 취득 과정 1차', 119);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2021. 02', '[블랜디드 수업]금오공대-퓨전360활용 제품제작 및 ACU 자격증 취득 과정 2차', 120);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2021. 05', '포항공대 나노융합기술원 고등학생 대상 ACU 국제인증자격시험 대비 특강 및 시험 응시', 121);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2021. 06', '강서 50플러스센터 3D프린터 입문 퓨전360을 활용한 제품제작 과정', 122);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2021. 07', '아이디어 제품분야 실전 창업교육', 123);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2021. 07', '[블랜디드 수업]금오공대 퓨전360활용 제품제작 및 3D프린팅과정', 124);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2021. 09', '경운대학교 Fusion360모델링 프로그램을 활용한 설계 및 장비운용과정', 125);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2021. 09', '포항나노융합기술원 퓨전360수업 및 ACU국제인증자격시험', 126);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2021. 11', '금오공대 지역사회와 함께하는 4차 산업혁명 대응 교육', 127);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 01', '금오공대 공학교육혁신센터 [퓨전360 모델링 설계 교육과정] 구체관절 캐릭터 3D프린팅 교육', 128);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 04', '김천동부초등학교 3D프린팅 및 3D펜 생생 직업체험 교육', 129);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 05', '한밭대학교 내일 꿈이룸학교 ACU 국제자격인증시험', 130);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 06', '옥수초등학교 학생대상 로봇공학자 진로체험학습', 131);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 07', '광주초월도서관 로봇공학자 진로체험 수업', 132);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 08', '별내중학교 학생 대상 코딩 전문가 진로체험수업', 133);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 09', '다산 새봄초등학교 6학년 학생 대상 코딩 전문가 진로체험수업', 134);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 10', '별망중학교 2학년 학생 대상 로봇공학자 진로체험학습', 135);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 11', '분당 장안중학교 학생대상 로봇전문가 진로체험학습', 136);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 11', '소현중학교 학생 대상 3D프린팅 전문가 진로체험학습', 137);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 12', '신동초등학교 학생 대상 로봇공학자 직업특강 프로그램 진로체험학습', 138);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 12', '군자 디지털 과학 고등학교 3D프린트 전문가 직업특강 프로그램', 139);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 12', '수원 이의고등학교 학생 대상 로봇공학자 진로체험학습', 140);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 12', '꿈나무마을 초록꿈터 [직업체험 박람회 프로그램] 3D프린터 체험학습', 141);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 12', '꿈나무마을 초록꿈터 [직업체험 박람회 프로그램] 코딩전문가 진로체험학습', 142);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2022. 12', '인천 당하초등학교 학생대상 3D프린터 전문가 진로체험학습', 143);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 01', '서울 올림픽파크텔 직업체험 프로그램 [3D프린터 체험학습]', 144);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 01', '서울 올림픽파크텔 직업박람회 직업체험 [로봇공학자 진로체험]', 145);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 01', '인천 혜광학교 중고등학생 대상 3D프린터 전문가 진로체험학습', 146);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 02', '금오공대 학생 대상 [퓨전360 모델링 설계 교육] 구체관절 캐릭터 과정', 147);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 04', '군포 태을초등학교 로봇공학자 진로체험학습', 148);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 05', '인평자동차고등학교 학생 대상 3D프린터전문가 진로체험학습', 149);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 06', '안산시 건강가정지원센터 3D프린터 직업 체험 프로그램', 150);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 06', '2023년 소상공인 전문기술교육', 151);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 07', '인천해양고등학교 학생대상 3D프린터 전문가 진로체험학습', 152);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 07', '구미 진평중학교 1,2,3학년 학생대상 3D프린터 전문강사 진로체험학습', 153);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 07', '화성 나루고등학교 학생대상 코딩전문가 진로체험학습 생생 직업체험', 154);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 07', '수원 이의고등학교 1,2학년 학생대상 로봇공학자 진로직업특강', 155);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 07', '화성학동초등학교 3학년 학생대상 로봇공학자 진로체험학습', 156);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 07', '효원문화연수원 로봇공학자 진로체험학습', 157);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 08', '원주미리내도서관 3D프린터 전문가 직업체험 프로그램 체험학습', 158);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 08', '화성서부종합사회복지관 초등학생 대상 로봇공학자 진로체험교육', 159);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 08', '화성서부종합사회복지관 초등학생 대상 3D프린터전문가 진로체험학습', 160);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 09', '인천세일고등학교 학생대상 로봇공학자 진로체험학습', 161);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 09', '강원아동복지센터 어린이 대상 3D프린터 진로체험학습', 162);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 09', '동인천고등학교 1,2학년 학생 대상 로봇공학자 진로체험수업', 163);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 09', '오산 화성초등학교 3~6학년 학생들 대상 3D프린터 전문가 진로체험학습', 164);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 09', '안산 상록초등학교 4학년 학생들 대상 로봇공학자 진로체험학습', 165);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 09', '월곡중학교 학생대상 로봇공학자 진로체험학습', 166);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 09', '경기항공과학고등학교 학생대상 로봇공학자 직업특강', 167);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 10', '오산초등학교 4학년 대상 로봇공학자 진로체험학습', 168);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 10', '용인 독정초등학교 학생 대상 로봇공학자 진로체험학습', 169);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 10', '시흥 신천초등학교 학생 대상 3D프린터 전문가 진로체험학습', 170);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 10', '시흥 신천초등학교 학생 대상 로봇 전문가 진로체험학습', 171);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 10', '오산 운암초등학교 5,6학년 학생 대상 3D프린터 전문가 진로체험학습', 172);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 10', '오산 운암초등학교 5,6학년 학생 대상 로봇공학자 진로체험학습', 173);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 10', '건국대학교 [혁신사업] fusion 360 모델링 프로그램을 활용한 제품설계 (acu 국제자격증)과정', 174);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 10', '용인 기흥 한얼초등학교 학생대상 로봇공학자 진로체험학습', 175);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 10', '안성중앙도서관 로봇공학자 진로체험학습', 176);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 10', '광명가족복지센터 아동대상 3D프린터 전문가 직업체험', 177);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 10', '의왕중앙도서관 저학년 학생 대상 로봇공학자 진로체험학습', 178);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 10', '성남정자초등학교 학생대상 로봇공학자 직업체험', 179);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 10', '구미시 HiVE센터 3D프린팅 전문가 과정 1회차', 180);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 11', '안동 경안여자고등학교 학생대상 3D프린트전문가 진로체험학습', 181);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 11', '인천제일고등학교 학생대상 로봇공학자 진로체험학습', 182);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 11', '광명 안서중학교 1학년 대상 3D프린터전문가 직업체험프로그램', 183);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 11', '용인 성산초등학교 3,4학년 학생 대상 로봇공학자 직업체험특강', 184);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 11', '안산 호원초등학교 학생대상 자율주행자동차 직업특강', 185);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 11', '용인 성산초등학교 5,6학년 학생대상 3D프린터전문가 진로체험', 186);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 11', '문경공업고등학교 1학년 학생대상 3D프린터전문가 진로체험교육', 187);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 11', '천안 두정초등학교 학생대상 로봇공학자 진로체험학습', 188);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 11', '금오공과대학교 [스마트제조 고급인력 양성사업]Fusion360을 활용한 3D모델링 교육', 189);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 11', '경기도 광주 송정초등학교 학생대상 로봇공학자 진로체험', 190);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 12', '광주 매곡초등학교 5학년 학생대상 로봇공학자 진로체험학습', 191);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 12', '안성 안법고등학교 학생대상 로봇전문가 진로체험학습', 192);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 12', '인천 영흥 중·고등학교 로봇공학자 진로체험학습', 193);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 12', '금오공대 [제조업 생산성 향상을 위한 리버스 엔지니어링 입문교육 with 3D scanning & 3D printing]', 194);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 12', '인천 중산초등학교 4학년 학생대상 코딩전문가 진로체험학습', 195);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 12', '금오공과대학교 [제품 디자인 및 제작 실무를 위한 Fusion 360 활용 3D모델링&3D프린팅교육]', 196);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 12', '남양주 양오중학교 학생대상 3D프린트전문가 진로체험학습', 197);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 12', '화성 향남고등학교 학생대상 로봇공학자 진로체험학습', 198);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2023. 12', '구미 인덕중학교 3학년 학생대상 3D프린트전문가 생생 직업체험프로그램', 199);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 01', '구미시 HiVE센터 3D프린팅 전문가 과정 2회차', 200);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 02', '건국대학교 스마트팩토리 아두이노를 활용한 RC카 제작', 201);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 02', '건국대학교 스마트팩토리 도트매트릭스 디자인 역량강화 교육', 202);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 02', '건국대학교 스마트팩토리 아두이노 활용 거짓말탐지기 제작교육', 203);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 05', '스마트제조고급인력양성사업-Fusion360을 활용한 3D모델링 수업_금오공과대학교 벤처창업관', 204);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 06', '2024년 소상공인 전문기술교육', 205);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 06', '구미 신당초등학교 3D프린터 직업 체험교육', 206);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 07', '[지역산업기반 인재양성 및 혁신기술개발 지원사업] Rhino를 활용한 3D모델링 교육 (금오공과대학교)', 207);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 07', '[산대특 : 제품개발을 위한 디자인 및 적층가공기술 엔지니어 양성과정]', 208);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 07', '[용인시 산업진흥원] 도시형소공인 집적직 장비 교육', 209);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 09', '부천원종초등학교 로봇공학자 전문가 수업', 210);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 10', '구미대학교 3D프린터운용기능사 대비과정 2차', 211);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 10', '양평청운초 로봇공학자 진로체험 수업', 212);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 10', '평택 송신초등학교 3D프린터 전문가 직업체험', 213);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 10', '용인 영문 중학교 로봇공학자 진로체험', 214);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 10', '성남 수성초등학교 로봇공학자 진로체험', 215);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 10', '늘푸른초등학교 코딩전문가 진로 체험 수업', 216);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 10', '수원신풍초등학교 3D펜 전문가 수업', 217);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 11', '[용인시산업진흥원]소공인복합지원센터 실무역량 강화교육 2차', 218);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 12', '[마산대학교] 3D프린터운용기능사 교육', 219);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2024. 12', '인천 부개고등학교 3D모델링 진로교육 꿈끼수업', 220);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2025. 04', '대구대학교 ROS 교육', 221);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2025. 04', '[한국폴리텍대학 진주캠퍼스] Fusion360 & FDM 3D프린팅 실무 집중 교육과정', 222);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2025. 05', '용인 수지도서관 메이커스페이스교육', 223);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2025. 05', '[용인시 산업진흥원] 도시형소공인 집적직 장비 교육_3D프린터 및 3D스캐너 마스터 과정 모집', 224);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2025. 05', '2025년 소상공인 전문기술교육', 225);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2025. 06', '연성대학교 치기공과 [3D프린팅 전문교강사 자격증 대비반]', 226);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2025. 06', '[관악구가족센터 은천점] 은천마루 3D펜 체험학습 교육', 227);
INSERT INTO education_performance (performed_at, title, sort_order) VALUES ('2025. 09', '연성대학교 치기공과 [3D프린팅 마스터 자격증 대비반]', 228);